development:
  sessions:
    default:
      database: mongoid-poc-development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: mongoid-poc-test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
